import type { Guide } from "@/types/guide";

export const guides: Guide[] = [
  {
    id: "guide-understanding-frame-time",
    slug: "understanding-frame-time",
    title: "Understanding FPS vs Frame Time: Why 60 FPS Still Stutters",
    excerpt: "Why a solid 60 FPS counter can still feel jittery and how frame time delivery variance causes micro-stutters.",
    description:
      "A deep technical exploration into mobile display rendering cadences. Learn why average frames-per-second counters mask micro-stutters, how SurfaceFlinger paces buffers to the display panel, and how to measure 1% low frame times accurately.",
    category: "FPS & Frame Time",
    contentType: "Explainer",
    difficulty: "Intermediate",
    author: { name: "Moha Gaming Lab Engineering", role: "Performance Architecture" },
    readingTimeMinutes: 7,
    publishedAt: "2026-06-10",
    updatedAt: "2026-08-20",
    version: "1.2.0",
    featured: true,
    tags: ["fps", "frame-time", "stutter", "surfaceflinger", "vsync", "pacing"],
    gameIds: ["pubg-mobile", "call-of-duty-mobile", "efootball"],
    toolIds: ["fps-monitor", "refresh-rate"],
    appIds: ["moha-fps-toolkit"],
    relatedGuideSlugs: ["diagnose-fps-drops-android", "why-120hz-does-not-mean-120-fps"],
    status: "published",
    summary: [
      "Average FPS averages frames over 1,000ms and hides individual frame stalls.",
      "A steady 60 FPS requires every frame to deliver in precisely 16.6 milliseconds.",
      "If 59 frames take 10ms but 1 frame takes 410ms, the counter reads ~59 FPS but the game visibly freezes for nearly half a second.",
      "1% low and 0.1% low metrics measure the slowest frames to expose real-world stutter.",
    ],
    sections: [
      {
        id: "the-mathematics-of-frame-time",
        title: "The Mathematics of Frame Time",
        level: "h2",
        paragraphs: [
          "Most mobile gamers evaluate performance solely by glancing at a floating FPS counter. If the counter reads '60', the natural assumption is that the game is running smoothly. However, human visual perception does not register an average — the human eye reacts to sudden irregularities in motion cadence.",
          "Frame time is the duration required by the GPU and CPU to compute, rasterize, and present a single individual frame. While FPS is an aggregate count of frames delivered over an entire 1,000ms second, frame time measures each frame individually in milliseconds (ms).",
        ],
        table: {
          caption: "Target Frame Time Cadence by Refresh Rate",
          headers: ["Target Frame Rate", "Display Refresh Interval", "Ideal Frame Time Delta"],
          rows: [
            ["30 FPS", "33.33 milliseconds", "± 1.0 ms"],
            ["60 FPS", "16.67 milliseconds", "± 0.5 ms"],
            ["90 FPS", "11.11 milliseconds", "± 0.3 ms"],
            ["120 FPS", "8.33 milliseconds", "± 0.2 ms"],
            ["144 FPS", "6.94 milliseconds", "± 0.2 ms"],
          ],
        },
      },
      {
        id: "the-micro-stutter-paradox",
        title: "The Micro-Stutter Paradox: Why 59 FPS Can Feel Unplayable",
        level: "h2",
        paragraphs: [
          "Consider a scenario in a fast-paced shooter like PUBG Mobile or Call of Duty: Mobile. Within a single one-second measurement window:",
          "59 frames are rendered at an ultra-fast 10ms each (totaling 590ms).",
          "Suddenly, an enemy throws a smoke grenade or a complex shader compiles, causing the 60th frame to stall for 410ms.",
          "The total elapsed time is 590ms + 410ms = 1,000ms. The total number of frames rendered is 60. A standard FPS counter will happily display 60 FPS (or 59 FPS). Yet the player just experienced a severe 410ms hitch right in the middle of a gunfight.",
        ],
        callout: {
          type: "important",
          title: "Technical Reality",
          content:
            "A game running at a perfectly paced 30 FPS (where every single frame arrives at exactly 33.3ms) will visually appear smoother and more responsive than an erratic 60 FPS game swinging between 8ms and 70ms.",
        },
      },
      {
        id: "surfaceflinger-and-vsync",
        title: "SurfaceFlinger & Android VSYNC Pacing",
        level: "h2",
        paragraphs: [
          "On Android devices, rendering is managed by the SurfaceFlinger system compositor. Android uses a triple-buffering system synchronized to Hardware VSYNC pulses generated by the display controller.",
          "When a frame misses its VSYNC deadline (for instance, taking 18ms instead of 16.6ms), SurfaceFlinger cannot present it to the screen on that scanout cycle. Instead, it must re-display the previous frame. This causes a dropped frame and visual stutter.",
        ],
        codeBlock: {
          language: "shell",
          code: "adb shell dumpsys SurfaceFlinger --latency <package_name>",
          caption: "Querying SurfaceFlinger Frame Timings via ADB",
          explanation:
            "Returns timestamp triples for each frame: desired presentation timestamp, actual presentation timestamp, and buffer latch time.",
        },
      },
      {
        id: "measuring-one-percent-lows",
        title: "How to Measure 1% Lows and Stutter",
        level: "h2",
        paragraphs: [
          "To objectively quantify smoothness, modern performance engineering relies on percentile statistics rather than arithmetic means:",
          "1% Low FPS: The average frame rate of the slowest 1% of all frames recorded. This directly reflects noticeable hitching.",
          "0.1% Low FPS: The average frame rate of the single worst 0.1% of frames, pinpointing catastrophic hitches such as asset streaming stalls or shader compilation lag.",
          "When your 1% low is close to your average FPS (e.g., average 60 FPS with 1% low of 57 FPS), motion feels rock solid. When your average is 60 FPS but your 1% low drops to 28 FPS, you are experiencing heavy micro-stutter.",
        ],
      },
      {
        id: "actionable-diagnostics",
        title: "Actionable Steps to Improve Frame Pacing",
        level: "h2",
        paragraphs: [
          "To stabilize erratic frame times without lowering visual fidelity excessively:",
        ],
        listItems: [
          "Lock frame rates to your panel's sustained capacity rather than setting 'Unlimited'.",
          "Lower volumetric effects, real-time shadows, and ragdoll physics, which frequently introduce transient CPU spikes.",
          "Preload game shaders in the lobby if the game supports it (e.g. Call of Duty Mobile's Shader Preload menu).",
          "Use our browser FPS / Frame-Time Monitor to evaluate rendering cadence directly on your device.",
        ],
        callout: {
          type: "tip",
          title: "Diagnostic Recommendation",
          content:
            "Test your device's browser rendering consistency using our live FPS / Frame-Time Monitor at /tools/fps-monitor before tweaking game configs.",
        },
      },
    ],
    faqs: [
      {
        question: "Can an in-game FPS counter show 60 while the game stutters?",
        answer:
          "Yes. Standard FPS counters average frame counts over 1,000ms. A single 200ms stall followed by fast frames still averages close to 60 FPS despite a severe visible hitch.",
      },
      {
        question: "What is an acceptable 1% low frame rate?",
        answer:
          "For competitive gaming, your 1% low should ideally remain above 85% of your target frame rate (e.g. at least 51 FPS on a 60 FPS cap, or 78 FPS on a 90 FPS cap).",
      },
    ],
  },
  {
    id: "guide-diagnose-fps-drops-android",
    slug: "diagnose-fps-drops-android",
    title: "How to Diagnose and Fix FPS Drops on Android",
    excerpt: "Systematic troubleshooting workflow for isolating CPU throttling, GPU saturation, and RAM pressure in mobile games.",
    description:
      "A structured diagnostic manual for identifying the exact cause of frame drops in mobile titles. Covers CPU vs GPU bottlenecks, thermal daemon throttling, background RAM paging, and verifiable optimization steps.",
    category: "Troubleshooting",
    contentType: "Troubleshooting",
    difficulty: "Intermediate",
    author: { name: "Moha Gaming Lab Engineering", role: "Performance Architecture" },
    readingTimeMinutes: 9,
    publishedAt: "2026-05-18",
    updatedAt: "2026-08-15",
    version: "1.3.0",
    featured: true,
    tags: ["fps-drops", "troubleshooting", "thermal", "governor", "ram", "diagnostics"],
    gameIds: ["pubg-mobile", "pubg-mobile-kr", "call-of-duty-mobile", "efootball"],
    toolIds: ["fps-monitor", "device-tier-checker", "gpu-test"],
    appIds: ["moha-fps-toolkit", "scene-android"],
    relatedGuideSlugs: ["understanding-frame-time", "android-gaming-thermal-throttling"],
    status: "published",
    summary: [
      "FPS drops stem from three distinct hardware bottlenecks: CPU thread stalls, GPU shader saturation, or thermal downclocking.",
      "FPS dropping after 10-15 minutes of play is almost always thermal throttling, not a game bug.",
      "Sudden frame drops when turning the camera indicate asset streaming or memory compaction stalls.",
      "Never disable Android thermal safety daemons; optimize game graphic load instead.",
    ],
    sections: [
      {
        id: "symptom-classification",
        title: "Step 1: Classify Your FPS Drop Symptoms",
        level: "h2",
        paragraphs: [
          "Before modifying settings randomly, pinpoint when and how the frame drop occurs. Different performance bottlenecks produce characteristic timing patterns:",
        ],
        table: {
          caption: "FPS Drop Patterns and Probable Causes",
          headers: ["Observed Symptom", "Probable Bottleneck", "Primary Suspect"],
          rows: [
            ["Drops only after 10–20 min of gameplay", "Thermal Throttling", "SoC thermal saturation / DVFS downclocking"],
            ["Stutters whenever rotating camera quickly", "Memory / Storage I/O", "Texture streaming stall or slow UFS storage"],
            ["Consistently low FPS regardless of duration", "GPU Bottleneck", "Resolution too high / complex post-processing"],
            ["Hitching during explosions or smoke", "CPU / Physics Bottleneck", "Particle simulation & draw call saturation"],
            ["Random stutter spikes every few minutes", "Background Process", "App sync / cloud backup / thermal polling"],
          ],
        },
      },
      {
        id: "triaging-thermal-throttling",
        title: "Step 2: Triaging Thermal Throttling",
        level: "h2",
        paragraphs: [
          "If your game runs at a flawless 60 or 90 FPS for the first 10 minutes, but gradually degrades into jitter and drops into the 40s, your device is hitting its thermal dissipation limit.",
          "Mobile processors have small passive cooling areas and a thermal envelope of roughly 4W to 6W. When internal die temperatures exceed threshold limits (typically 42°C–45°C skin temperature), the kernel downclocks prime CPU and GPU clusters to prevent battery damage.",
        ],
        callout: {
          type: "warning",
          title: "Critical Safety Warning",
          content:
            "Never flash Magisk modules or run scripts that delete or disable thermal-engine or thermal_manager. Bypassing thermal limits can cause permanent battery degradation, screen adhesive separation, or motherboard damage.",
        },
      },
      {
        id: "low-risk-fixes",
        title: "Step 3: Low-Risk Optimization Workflow",
        level: "h2",
        paragraphs: [
          "Follow this ordered sequence of verified optimizations to recover sustained frame stability:",
        ],
        listItems: [
          "Lower in-game Graphics preset to 'Smooth' or 'Low' while setting Frame Rate to its maximum available value (90 FPS or 120 FPS). This minimizes GPU shading load while preserving maximum refresh responsiveness.",
          "Disable in-game Anti-Aliasing (MSAA). Multisample anti-aliasing forces the mobile GPU to calculate multiple color samples per pixel, dramatically increasing bandwidth load on unified mobile RAM.",
          "Turn off Auto-Adjust Graphics. This feature automatically toggles settings during combat, ironically introducing stutter spikes as assets reload.",
          "Remove heavy phone cases during ranked sessions to facilitate passive radiant heat dissipation from the aluminum/glass back panel.",
        ],
      },
      {
        id: "elevated-tuning",
        title: "Step 4: Advanced Tuning with Elevated Utilities",
        level: "h2",
        paragraphs: [
          "For power users utilizing utilities like Shizuku or Scene:",
        ],
        codeBlock: {
          language: "shell",
          code: "adb shell cmd package compile -m speed -f <package_name>",
          caption: "AOT Compilation Command via ADB",
          explanation:
            "Forces Android's ART runtime to pre-compile the game's bytecode to native machine code, eliminating JIT compilation pauses during gameplay.",
        },
        callout: {
          type: "tip",
          title: "Pre-compilation Tip",
          content:
            "Running ART speed compilation significantly reduces micro-stutters in Unreal Engine titles like eFootball and PUBG Mobile after major game updates.",
        },
      },
    ],
    faqs: [
      {
        question: "Why do game booster apps rarely fix FPS drops?",
        answer:
          "Many commercial booster apps merely clear cached memory or kill background apps that Android immediately restarts. Real FPS drops are caused by thermal downclocking or GPU shader saturation, which RAM cleaners cannot resolve.",
      },
      {
        question: "Does lowering screen resolution improve FPS?",
        answer:
          "Yes. Lowering render resolution dramatically cuts GPU fillrate demands and memory bandwidth, enabling the GPU to sustain higher clock rates with less heat generation.",
      },
    ],
  },
  {
    id: "guide-why-120hz-does-not-mean-120-fps",
    slug: "why-120hz-does-not-mean-120-fps",
    title: "Why 120Hz Does Not Always Mean 120 FPS",
    excerpt: "Demystifying mobile high-refresh panels: panel scanout versus GPU rendering rate and dynamic LTPO throttling.",
    description:
      "A clear technical breakdown of the difference between display refresh rate (Hz) and game frame rate (FPS). Explains Android Choreographer synchronization, OEM LTPO downclocking, and why a 120Hz display may still present 60 FPS gameplay.",
    category: "Performance",
    contentType: "Explainer",
    difficulty: "Beginner",
    author: { name: "Moha Gaming Lab Engineering", role: "Display Systems" },
    readingTimeMinutes: 6,
    publishedAt: "2026-07-04",
    updatedAt: "2026-08-10",
    version: "1.1.0",
    featured: true,
    tags: ["120hz", "refresh-rate", "fps", "ltpo", "display", "hz-vs-fps"],
    gameIds: ["pubg-mobile", "call-of-duty-mobile"],
    toolIds: ["refresh-rate", "display-test", "fps-monitor"],
    appIds: ["refresh-rate-switcher"],
    relatedGuideSlugs: ["understanding-frame-time", "touch-latency-input-delay-guide"],
    status: "published",
    summary: [
      "Refresh rate (Hz) is how many times per second the physical screen refreshes its pixels.",
      "Frame rate (FPS) is how many completed image buffers the GPU actually draws.",
      "Playing a 60 FPS game on a 120Hz screen simply displays each completed frame twice.",
      "Many Android OEM ROMs force-lock games to 60Hz to conserve battery, ignoring your 120Hz display setting.",
    ],
    sections: [
      {
        id: "the-fundamental-distinction",
        title: "The Core Difference: Refresh Rate vs Frame Rate",
        level: "h2",
        paragraphs: [
          "One of the most widespread misconceptions among mobile gamers is believing that purchasing a phone advertised with a '120Hz AMOLED display' automatically guarantees 120 FPS in all their games.",
          "The physical refresh rate (measured in Hertz, Hz) is a hardware characteristic of the display panel. It dictates how many times per second the display controller reads out a frame from the frame buffer and updates the screen's light-emitting diodes.",
          "The frame rate (measured in Frames Per Second, FPS) is a software execution rate. It represents how many finished image frames the CPU and GPU are capable of rendering within a given second.",
        ],
      },
      {
        id: "what-happens-at-60-fps-on-120hz",
        title: "What Happens When You Play a 60 FPS Game on a 120Hz Screen?",
        level: "h2",
        paragraphs: [
          "If a game engine is capped at 60 FPS (such as eFootball Mobile or Genshin Impact), but your display is running at 120Hz:",
          "The screen refreshes 120 times every second (once every 8.33ms).",
          "However, the game GPU only produces a new frame once every 16.67ms.",
          "As a result, SurfaceFlinger simply displays each rendered frame for two consecutive refresh cycles. The game does not look twice as smooth; it still moves at 60 frames per second.",
        ],
        callout: {
          type: "note",
          title: "Input Latency Benefit",
          content:
            "Even when a game is locked to 60 FPS, running a 120Hz panel offers a minor reduction in display input lag. The scanout window is only 8.33ms wide, meaning completed frames can reach your eyes up to 8ms sooner than on a 60Hz panel.",
        },
      },
      {
        id: "oem-ltpo-throttling",
        title: "Why Your Phone Drops to 60Hz in Games",
        level: "h2",
        paragraphs: [
          "Many modern flagship devices from Samsung, Xiaomi, and OnePlus utilize LTPO (Low-Temperature Polycrystalline Oxide) displays that dynamically adjust refresh rates from 1Hz to 120Hz to conserve battery.",
          "Unfortunately, OEM software daemons frequently classify gaming apps as high-power workloads and silently force the display down to 60Hz, completely overriding your system refresh rate settings.",
          "Even if PUBG Mobile supports 90 FPS, the phone panel drops to 60Hz, capping what you actually see to 60 FPS.",
        ],
        callout: {
          type: "tip",
          title: "Testing Your True Rate",
          content:
            "Use our browser Refresh Rate Test tool at /tools/refresh-rate to inspect the rendering rate your browser and OS are presenting to the screen right now.",
        },
      },
    ],
    faqs: [
      {
        question: "Can I force 120Hz in games that OEM software locks to 60Hz?",
        answer:
          "Yes. Utilities like our Display Refresh Rate Switcher or Shizuku can write to the Android WRITE_SECURE_SETTINGS table to lock peak_refresh_rate and min_refresh_rate to 120Hz.",
      },
    ],
  },
  {
    id: "guide-mobile-gaming-network-latency-jitter",
    slug: "mobile-gaming-network-latency-jitter",
    title: "Mobile Gaming Network Latency & Jitter: How to Lower Ping",
    excerpt: "Why in-game ping spikes occur, the difference between ICMP and UDP latency, and how to eliminate mobile packet jitter.",
    description:
      "A comprehensive guide to mobile gaming network performance. Explains round-trip time (RTT), packet jitter standard deviation, Wi-Fi channel congestion, cellular bufferbloat, and verified network optimization techniques.",
    category: "Network",
    contentType: "Guide",
    difficulty: "Intermediate",
    author: { name: "Moha Gaming Lab Engineering", role: "Network Architecture" },
    readingTimeMinutes: 8,
    publishedAt: "2026-07-22",
    updatedAt: "2026-08-18",
    version: "1.2.0",
    featured: true,
    tags: ["network", "ping", "latency", "jitter", "wifi", "dns", "packet-loss"],
    gameIds: ["pubg-mobile", "pubg-mobile-kr", "call-of-duty-mobile"],
    toolIds: ["network-test", "ping-tester"],
    appIds: ["moha-network-monitor", "netguard-gaming"],
    relatedGuideSlugs: ["diagnose-fps-drops-android"],
    status: "published",
    summary: [
      "In-game ping is UDP round-trip time between your device and the regional game server.",
      "Jitter (variance in latency) is more disruptive than steady high ping, causing bullets to desync and players to teleport.",
      "2.4GHz Wi-Fi suffers from Bluetooth interference and crowded airwaves; 5GHz/6GHz is mandatory for mobile gaming.",
      "Bufferbloat occurs when home network uploads fill router buffers, causing latency to spike from 20ms to 400ms.",
    ],
    sections: [
      {
        id: "ping-fundamentals",
        title: "The Anatomy of Mobile Gaming Latency",
        level: "h2",
        paragraphs: [
          "In online multiplayer games like PUBG Mobile and Call of Duty: Mobile, the displayed ping represents the round-trip time (RTT) required for a UDP packet containing your player inputs to travel to the game server and for the server's state packet to return.",
          "Unlike web browsing or video streaming, which use reliable TCP connections that retransmit lost packets, competitive games transmit game state over UDP (User Datagram Protocol). If a UDP packet arrives too late or is dropped, the server cannot wait — resulting in 'rubber-banding' and lost hit registration.",
        ],
      },
      {
        id: "the-threat-of-jitter",
        title: "Why Jitter is Deadlier Than High Ping",
        level: "h2",
        paragraphs: [
          "A consistent 60ms ping is predictable. The game engine's client-side prediction algorithms can accurately extrapolate player positions and weapon trajectories.",
          "Jitter is the variance in latency from packet to packet. If your ping fluctuates between 30ms and 150ms every couple of seconds:",
          "Client-side prediction breaks down.",
          "The server rewinds your player position (rubber-banding).",
          "Enemy hitboxes desynchronize from their visual models, causing your bullets to seemingly 'ghost' straight through opponents.",
        ],
        callout: {
          type: "important",
          title: "Benchmark Standard",
          content:
            "In competitive esports, jitter standard deviation should remain below 5ms. Any jitter above 15ms will result in erratic hit registration.",
        },
      },
      {
        id: "wifi-vs-cellular",
        title: "Wi-Fi Frequency Bands and Wireless Congestion",
        level: "h2",
        paragraphs: [
          "Wi-Fi frequency selection is the single largest factor under a player's direct control:",
          "2.4GHz Wi-Fi shares the exact same radio frequency spectrum as Bluetooth (used by wireless earphones and controllers) and microwave ovens. It has only 3 non-overlapping channels (1, 6, 11), making packet collisions nearly inevitable.",
          "5GHz Wi-Fi offers 24+ non-overlapping channels with significantly wider bandwidth and virtually zero Bluetooth interference. Switching from 2.4GHz to 5GHz frequently drops jitter by 80%.",
        ],
      },
      {
        id: "bufferbloat-mitigation",
        title: "Bufferbloat: The Hidden Cause of In-Match Spikes",
        level: "h2",
        paragraphs: [
          "Bufferbloat occurs when standard consumer routers buffer too many packets during heavy home bandwidth usage (e.g. someone streaming 4K video or uploading files). The router queues your tiny 64-byte gaming packet behind massive video buffers, causing your ping to spike from 25ms to 300ms+.",
          "To combat bufferbloat, enable Smart Queue Management (SQM) or Cake QoS on your router, or use NetGuard on your phone to block background apps from hogging bandwidth during matches.",
        ],
      },
    ],
    faqs: [
      {
        question: "Does changing DNS lower in-game ping?",
        answer:
          "Changing DNS only speeds up the initial domain name resolution when finding the server. It does NOT lower your in-game gameplay ping, which is determined by physical routing hops.",
      },
      {
        question: "Is 5G mobile data better than Wi-Fi for gaming?",
        answer:
          "A strong 5GHz Wi-Fi connection usually has lower jitter than 5G cellular, which is subject to tower handoffs and variable radio signal reflections.",
      },
    ],
  },
  {
    id: "guide-android-gaming-thermal-throttling",
    slug: "android-gaming-thermal-throttling",
    title: "Android Gaming Thermal Throttling: Causes, Mitigation & Governor Tuning",
    excerpt: "In-depth guide to mobile SoC thermal envelopes, big/LITTLE CPU cluster downclocking, and safe governor configuration.",
    description:
      "A hardware-level guide explaining mobile silicon thermal design power (TDP), thermal throttling sequences on Snapdragon and Dimensity chips, and how to configure sustained performance governors without risking hardware damage.",
    category: "Thermals",
    contentType: "Tutorial",
    difficulty: "Advanced",
    author: { name: "Moha Gaming Lab Engineering", role: "Silicon Architecture" },
    readingTimeMinutes: 10,
    publishedAt: "2026-08-01",
    updatedAt: "2026-08-25",
    version: "1.0.0",
    featured: false,
    tags: ["thermals", "throttling", "governor", "tdp", "cpu", "kernel", "root"],
    gameIds: ["pubg-mobile", "call-of-duty-mobile", "efootball"],
    toolIds: ["gpu-test", "fps-calculator", "device-tier-checker"],
    appIds: ["scene-android", "franco-kernel-manager"],
    relatedGuideSlugs: ["diagnose-fps-drops-android", "understanding-frame-time"],
    status: "published",
    summary: [
      "Smartphones lack active fans; internal SoCs can only dissipate 4W–6W of heat through the chassis.",
      "Peak benchmark clocks (e.g. 3.3 GHz) can only be sustained for 3 to 5 minutes before thermal throttles trigger.",
      "Thermal daemons throttle the Prime/big cores first, then throttle the GPU frequency in steps.",
      "An external Peltier cooler or lowered resolution delivers far more sustained performance than aggressive kernel overclocks.",
    ],
    sections: [
      {
        id: "the-4-watt-envelope",
        title: "The Reality of Mobile Thermal Design Power (TDP)",
        level: "h2",
        paragraphs: [
          "Desktop gaming PCs dissipate 250W to 450W using massive heat sinks and multiple high-CFM fans. Modern flagship smartphones pack SoCs (like the Snapdragon 8 Gen 3 or Dimensity 9300) capable of pulling 10W to 14W at peak burst clocks.",
          "However, a smartphone chassis held in human hands can only passively dissipate between 4.0W and 5.5W of continuous thermal energy before the device becomes uncomfortably hot to touch (> 45°C skin temperature).",
          "Therefore, every mobile flagship is fundamentally designed to throttle. The question is not IF it throttles, but HOW GRACEFULLY it manages the throttling curve.",
        ],
      },
      {
        id: "throttling-sequence",
        title: "The Android Kernel Throttling Sequence",
        level: "h2",
        paragraphs: [
          "When the device's internal thermistors (located near the battery, PMIC, and CPU die) detect temperatures crossing threshold limits, the kernel's thermal daemon initiates a multi-stage downclocking routine:",
          "Stage 1 (40°C internal): Prime Cortex-X cores downclock from 3.3GHz to ~2.6GHz.",
          "Stage 2 (43°C internal): GPU frequency steps down (e.g. from 900MHz to 680MHz). Frame rates drop from 90 FPS to 75 FPS.",
          "Stage 3 (46°C internal): Heavy thermal mitigation. Prime core is gated; middle cores downclock to 1.8GHz; GPU steps to minimum power tier. The game drops into the 40s with severe stutter.",
        ],
        callout: {
          type: "warning",
          title: "Do Not Bypass Thermal Daemons",
          content:
            "Disabling thermal daemons via root scripts forces chips to run at max frequencies until the hardware undergoes sudden emergency power-off shutdown, rapidly destroying lithium-ion battery capacity.",
        },
      },
      {
        id: "governor-tuning",
        title: "Sustained Governor Tuning with Scene / FKM",
        level: "h2",
        paragraphs: [
          "Instead of fighting thermal limits, tune your CPU governors for flat, sustained power delivery:",
          "Using tools like Scene 7 or Franco Kernel Manager, lock your big CPU clusters to 75%–80% of their peak frequency (e.g. capping a 3.0GHz core at 2.4GHz).",
          "Because power consumption scales non-linearly with frequency (P ∝ V²f), dropping clocks by 20% can reduce thermal heat output by over 40%.",
          "The SoC runs cooler, avoids hitting emergency thermal trip points, and delivers rock-solid, uninterrupted 60 or 90 FPS for hours.",
        ],
      },
    ],
    faqs: [
      {
        question: "Do phone cooling fans (Peltier coolers) actually work?",
        answer:
          "Yes. Active thermoelectric (Peltier) coolers directly chill the back glass, absorbing 5W+ of heat and allowing SoCs to sustain peak clock frequencies indefinitely without thermal throttling.",
      },
    ],
  },
  {
    id: "guide-touch-latency-input-delay-guide",
    slug: "touch-latency-input-delay-guide",
    title: "Touch Latency & Input Delay in Mobile Shooters",
    excerpt: "Analyzing the end-to-end touch pipeline: digitizer sampling rates, Android input queues, and graphics pipeline delay.",
    description:
      "A technical investigation into touch latency for competitive mobile shooters. Explains digitizer polling rates (120Hz/240Hz/480Hz), Android input event dispatch, rendering queue latency, and practical tweaks to shave off milliseconds.",
    category: "Touch & Input",
    contentType: "Guide",
    difficulty: "Intermediate",
    author: { name: "Moha Gaming Lab Engineering", role: "Input Systems" },
    readingTimeMinutes: 7,
    publishedAt: "2026-08-12",
    updatedAt: "2026-08-28",
    version: "1.0.0",
    featured: false,
    tags: ["touch-latency", "input-delay", "digitizer", "polling-rate", "shooters", "pubg"],
    gameIds: ["pubg-mobile", "call-of-duty-mobile"],
    toolIds: ["touch-test", "display-test"],
    appIds: ["moha-fps-toolkit"],
    relatedGuideSlugs: ["understanding-frame-time", "why-120hz-does-not-mean-120-fps"],
    status: "published",
    summary: [
      "End-to-end touch latency is the total delay between your finger contacting the glass and the corresponding pixel lighting up.",
      "A 240Hz touch digitizer reads inputs every 4.16ms, but overall system latency is often 30ms to 60ms due to rendering queues.",
      "High graphic settings and post-processing increase the GPU queue depth, directly increasing input lag.",
      "Bluetooth audio can add 150ms–250ms of audio latency, leading players to perceive visual input delay.",
    ],
    sections: [
      {
        id: "the-touch-pipeline",
        title: "The End-to-End Touch Latency Pipeline",
        level: "h2",
        paragraphs: [
          "In competitive first-person shooters, winning a duel often comes down to who shoots first by a margin of 10 to 30 milliseconds. Many gamers believe that a phone with a '480Hz touch sampling rate' guarantees instantaneous response.",
          "However, digitizer sampling is only the very first link in a multi-stage input chain:",
          "1. Digitizer Scan: The capacitive sensor grid samples finger position (e.g. 240Hz = 4.16ms delay).",
          "2. Kernel Input Subsystem: The touch IC sends an interrupt to the Linux kernel /dev/input/event node (1ms–2ms).",
          "3. Android WindowManager: The system dispatches the MotionEvent to the focused app window (2ms–4ms).",
          "4. Game Engine Update: The game processes the input in its tick loop (8ms–16ms).",
          "5. GPU Render Queue: The frame is queued, rasterized, and submitted to SurfaceFlinger (8ms–16ms).",
          "6. Display Scanout: The panel updates pixels row by row (8ms–16ms).",
          "Total end-to-end latency typically spans 30ms to 55ms on high-end phones, and 70ms+ on budget hardware.",
        ],
      },
      {
        id: "polling-rate-vs-queue",
        title: "Digitizer Polling Rates Explained",
        level: "h2",
        paragraphs: [
          "Higher touch sampling rates (240Hz, 360Hz, 480Hz) improve motion tracking fidelity and reduce the initial scan latency, smoothing out micro-aiming adjustments with your thumb.",
          "However, if your game is rendering at 30 FPS, the game engine only samples input state once every 33.3ms. Having a 480Hz digitizer cannot overcome a slow rendering pipeline.",
        ],
        callout: {
          type: "important",
          title: "Golden Rule of Input Lag",
          content:
            "Increasing your frame rate from 60 FPS to 90 FPS reduces input lag by over 5.5ms on every single frame, having a far greater impact on aiming responsiveness than upgrading from a 240Hz to a 480Hz screen.",
        },
      },
      {
        id: "practical-touch-tuning",
        title: "Practical Steps to Minimize Touch Delay",
        level: "h2",
        paragraphs: [
          "To achieve the crispest, lowest-latency touch response:",
        ],
        listItems: [
          "Lower graphics to 'Smooth' to reduce GPU rendering queue depth to minimum latency.",
          "Enable OEM Touch Optimization / Game Turbo high-sensitivity mode in system settings.",
          "Clean glass screen protectors: thick, low-grade tempered glass dampens capacitive signal strength, causing dropped or delayed touch events.",
          "Use our browser Touch / Pointer Test at /tools/touch-test to inspect pointer event dispatch frequencies on your device.",
        ],
      },
    ],
    faqs: [
      {
        question: "Does high touch sampling rate drain battery faster?",
        answer:
          "Yes, running digitizers at 480Hz or higher increases touch IC power consumption slightly, but in-game it accounts for less than 3% of total battery draw.",
      },
    ],
  },
];

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}

export function getFeaturedGuides(): Guide[] {
  return guides.filter((g) => g.featured);
}
